<% bom_attr_num_list = DataItem.get_item_list(@current_user, 'num') %>
<% bom_attr_text_list = DataItem.get_item_list(@current_user, 'text') %>
<% bom_attr_date_list = DataItem.get_item_list(@current_user, 'date') %>
---
:grid:
  :id: id_impoted_bom_grid
  :var: var_imported_bom_grid
  :xtype: Ext.grid.GridPanel
  :title: <%= t('bom.bom_info_grid_title') %>
  :stripeRows: true
  :width: 100%
  :height: 500
  #:autoWidth: true
  #:autoHeight: true
  :loadMask: true
  :bbar:
    :pageSize: 400
    :displayMsg: Display:{0}-{1} of {2}
    :emptyMsg: No Data
:grid_view:
  :var: ext_imported_bom_grid_view
  :xtype: Ext.grid.GridView
  :forceFit: false
:SelectionModel:
  :var: ext_imopted_grid_selmodel
  :xtype: Ext.grid.RowSelectionModel
  :singleSelect: true
:Store:
  :var: ext_impoted_bom_grid_store
  :storeId: impoted_bom_grid_store
  :url: <%= url_for(:controller=>:fuji, :action=>:get_bom_info) %>
  :totalProperty: total
  :record: row
  :idPath: bom_id
  :fields:
  - :name: bom_id
    :mapping: bom_id
  - :name: product_id
    :mapping: product_id
  - :name: parts_key_no
    :mapping: parts_key_no
  - :name: lv
    :mapping: lv
  - :name: parts_name
    :mapping: parts_name
  - :name: qty_parent
    :mapping: qty_parent
  - :name: qty_all
    :mapping: qty_all
  - :name: unit_cost
    :mapping: unit_cost
  - :name: cost
    :mapping: cost
  - :name: lead_time
    :mapping: lead_time
<% bom_attr_num_list.each do |at| %>
  - :name: <%= at.attr_type.to_s+at.seq.to_s %>
    :mapping: <%= at.attr_type.to_s+at.seq.to_s %>
<% end %>
<% bom_attr_text_list.each do |at| %>
  - :name: <%= at.attr_type.to_s+at.seq.to_s %>
    :mapping: <%= at.attr_type.to_s+at.seq.to_s %>
<% end %>
<% bom_attr_date_list.each do |at| %>
  - :name: <%= at.attr_type.to_s+at.seq.to_s %>
    :mapping: <%= at.attr_type.to_s+at.seq.to_s %>
<% end %>
  - :name: man_start_date
    :mapping: man_start_date
  - :name: delivery_date
    :mapping: delivery_date
  - :name: lft
    :mapping: lft
  - :name: rgt
    :mapping: rgt
  - :name: visible
    :mapping: visible
  - :name: subopen
    :mapping: subopen
:colModel:
  :var: ext_bom_info_grid_colmodel
  :defaults:
    :sortable: false
    :menuDisabled: true
  :columns:
  - :dataIndex: bom_id
    :header: bom_id
    :hidden: true
  - :dataIndex: product_id
    :header: product_id
    :hidden: true
  - :dataIndex: parts_key_no
    :header: <%= t('bom.parts_key_no') %>
    :width: 125
    :renderer: "function (value, p, record){
                              var disp = value;
                              for(var i=0;i<record.data.lv;i++) {disp = '　　' + disp;}
                              return disp;
                            }"
  - :dataIndex: lv
    :header: Level
    :hidden: true
  - :dataIndex: parts_name
    :header: <%= t('bom.parts_name') %>
    :width: 175
  - :dataIndex: qty_parent
    :header: <%= t('bom.qty_parent') %>
    :width: 100
    :align: right
  - :dataIndex: qty_all
    :header: <%= t('bom.qty_all') %>
    :width: 75
    :align: right
  - :dataIndex: lead_time
    :header: <%= t('bom.lead_time') %>
    :width: 75
    :align: right
    :editor:
  - :dataIndex: man_start_date
    :header: <%= t('bom.man_start_date') %>
    :width: 100
  - :dataIndex: delivery_date
    :header: <%= t('bom.delivery_date') %>
    :width: 100
  - :dataIndex: unit_cost
    :header: <%= t('bom.unit_cost') %>
    :width: 75
    :align: right
  - :dataIndex: cost
    :header: <%= t('bom.gross_cost') %>
    :width: 75
    :align: right
<% bom_attr_num_list.each do |at| %>
  - :dataIndex: <%= at.attr_type.to_s+at.seq.to_s %>
    :header: <%= at.attr_name %>
    :width: 75
    :align: right
<% end %>
<% bom_attr_text_list.each do |at| %>
  - :dataIndex: <%= at.attr_type.to_s+at.seq.to_s %>
    :header: <%= at.attr_name %>
    :width: 125
<% end %>
<% bom_attr_date_list.each do |at| %>
  - :dataIndex: <%= at.attr_type.to_s+at.seq.to_s %>
    :header: <%= at.attr_name %>
    :width: 100
<% end %>
